type Metric = { mom: number | null; yoy: number | null; mom_3m_ann: number | null; mom_6m_ann: number | null; date: string | null };
type Cpi = { release_month?: string | null; headline?: Metric; core?: Metric; contributors?: { category: string; mom: number | null; w1?: string | null }[]; breadth?: { eligible_components?: number; rising_mom?: number; rising_above_0_2?: number; rising_above_0_4?: number; declining_mom?: number }; nowcast?: { source_status?: string; note?: string }; takeaway?: { text?: string } };
const pct = (value: number | null | undefined) => value == null ? 'N/A' : `${value >= 0 ? '+' : ''}${value.toFixed(1)}%`;
export function CpiPanel({ cpi }: { cpi?: Cpi }) {
  if (!cpi) return null;
  const available = typeof cpi.headline?.mom === 'number' && typeof cpi.core?.mom === 'number';
  const top = (cpi.contributors ?? []).filter((item) => item.mom != null).sort((a, b) => Math.abs(b.mom as number) - Math.abs(a.mom as number)).slice(0, 5);
  return <section className="cpi-panel"><div className="cpi-heading"><h2>CPI — What drove the latest print?</h2><small>{cpi.release_month ?? 'Latest release'} · Official BLS</small></div><p className="section-summary"><strong>{cpi.takeaway?.text ?? 'Headline and core inflation are shown with their latest official category moves.'}</strong></p>{available ? <><div className="cpi-summary"><article><small>Headline CPI</small><strong>{pct(cpi.headline?.mom)}</strong><span>{pct(cpi.headline?.yoy)} YoY · 3M {pct(cpi.headline?.mom_3m_ann)} annualized</span></article><article><small>Core CPI</small><strong>{pct(cpi.core?.mom)}</strong><span>{pct(cpi.core?.yoy)} YoY · 3M {pct(cpi.core?.mom_3m_ann)} annualized</span></article><article><small>Breadth</small><strong>{cpi.breadth?.rising_mom ?? 'N/A'} / {cpi.breadth?.eligible_components ?? 'N/A'} rising</strong><span>{cpi.breadth?.declining_mom ?? 'N/A'} declining this month</span></article></div><div className="cpi-detail"><div><b>Largest contributors to headline CPI</b><small>Official BLS effects on the monthly All Items CPI. Nested categories such as gasoline and energy must not be added together.</small>{top.map((item) => <span key={item.category}><small>{item.category.replace(/_/g, ' ')}</small><strong>{item.w1 == null ? 'Effect unavailable' : `${Number(item.w1).toFixed(3)} percentage points`}</strong></span>)}</div><aside><b>Next CPI nowcast — not official BLS data</b><p>{cpi.nowcast?.source_status === 'live_page_retrieved' ? 'Public model page retrieved; numeric nowcast values were not reliably exposed.' : 'Currently unavailable.'}</p><small>{cpi.nowcast?.note ?? 'Model-based estimate, not official BLS data.'}</small></aside></div><div className="cpi-why"><b>Why it matters</b><span>Inflation broadened across selected components, but gasoline and several unusually large moves disproportionately lifted the headline.</span></div></> : <p className="cpi-unavailable">Official BLS CPI data is temporarily unavailable; no unsupported release values are shown.</p>}</section>;
}
