import type { DashboardData } from '../types/dashboard';
import { CpiPanel } from './CpiPanel';

export function MacroHero({ data }: { data: DashboardData }) {
  const counts = data.indicators.reduce((result, indicator) => { if (indicator.score !== null) result[indicator.score] += 1; return result; }, [0, 0, 0]);
  const scored = data.indicators.filter((indicator) => indicator.scored).length;
  const updated = new Date(data.generated_at).toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
  const inflation = (data as DashboardData & { inflation_release?: Parameters<typeof CpiPanel>[0]['cpi'] }).inflation_release;
  return <><section className="macro-hero"><div className="macro-hero__art" aria-hidden="true"><div className="macro-hero__sun" /><div className="macro-hero__skyline" /><div className="macro-hero__capitol"><span /><span /><span /><span /><span /></div></div><header className="macro-hero__title"><div className="eyebrow">MACRO MONITOR · UNITED STATES</div><h1>US Recession Risk Dashboard</h1><p>A multi-signal view of the U.S. economic cycle, financial stress, and market vulnerability.</p><small>Last updated · {updated} · Model v{(data as DashboardData & { score_model_version?: number }).score_model_version ?? 1} · {data.data_status === 'ok' ? 'Live data' : 'Sample data'}</small></header><div className="macro-hero__scene"><div className="macro-hero__gauge"><div className="macro-hero__arc"><span className="macro-hero__needle" style={{ '--score-angle': `${-90 + data.risk_score * 1.8}deg` } as React.CSSProperties} /></div><div className="macro-hero__labels"><span>Healthy</span><span>Slowdown</span><span>Recession</span></div><div className="macro-hero__score-plate"><span>Cycle Risk Score</span><strong>{data.risk_score}<small>/ 100</small></strong><b>{data.regime}</b><div><span>{data.total_score} of {data.max_score} risk points</span><span>{scored} scored indicators</span></div></div></div><aside className="macro-hero__stress"><span>Current Stress</span><strong>{data.current_stress?.state ?? 'Unavailable'}</strong><small>{data.current_stress?.active_confirmations ?? 0} / 6 confirmations</small><em>Separate from Cycle Risk</em></aside></div><div className="macro-hero__counts"><span><i className="dot healthy" />{counts[0]} Healthy</span><span><i className="dot warning" />{counts[1]} Warning</span><span><i className="dot recessionary" />{counts[2]} Recessionary</span></div></section><CpiPanel cpi={inflation} /></>;
}
