type Tenor = { label: string; yield: number | null; observation_date: string | null };
type Curve = { as_of: string | null; mixed_dates: boolean; tenors: Tenor[]; spreads: { id: string; label: string; basis_points: number | null }[]; shape: string; movement: string; historical: Record<string, { representative_date: string | null; coverage: string; tenors: Tenor[] }> };

export function TreasuryCurvePanel({ curve }: { curve?: Curve }) {
  if (!curve) return null;
  const points = curve.tenors.filter((tenor) => tenor.yield !== null);
  const min = Math.min(...points.map((point) => point.yield as number), 0);
  const max = Math.max(...points.map((point) => point.yield as number), 1);
  const width = 720; const height = 220; const pad = 34;
  const x = (index: number) => pad + (index / Math.max(points.length - 1, 1)) * (width - pad * 2);
  const y = (value: number) => height - pad - ((value - min) / Math.max(max - min, 0.01)) * (height - pad * 2);
  const path = points.map((point, index) => `${index ? 'L' : 'M'} ${x(index)} ${y(point.yield as number)}`).join(' ');
  return <div className="treasury-curve-panel"><div className="curve-panel-heading"><div><b>Full Treasury curve</b><small>{curve.as_of} · {curve.mixed_dates ? 'mixed observation dates' : 'aligned observation date'}</small></div><span>{curve.shape.replace(/_/g, ' ')} · {curve.movement.replace(/_/g, ' ')}</span></div><div className="curve-chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Treasury yields from 1 month to 30 years"><path className="curve-gridline" d={`M ${pad} ${height-pad} H ${width-pad}`} /><path className="curve-line" d={path} />{points.map((point, index) => <circle key={point.label} cx={x(index)} cy={y(point.yield as number)} r="4"><title>{`${point.label}: ${(point.yield as number).toFixed(2)}% · ${point.observation_date}`}</title></circle>)}</svg></div><div className="curve-tenor-row">{points.map((point) => <span key={point.label}><b>{point.label}</b><strong>{(point.yield as number).toFixed(2)}%</strong><small>{point.observation_date}</small></span>)}</div><div className="curve-spreads">{curve.spreads.map((spread) => <span key={spread.id}><small>{spread.label}</small><b>{spread.basis_points === null ? '—' : `${spread.basis_points >= 0 ? '+' : ''}${spread.basis_points.toFixed(0)} bp`}</b></span>)}</div><p className="curve-takeaway"><strong>{curve.shape === 'inverted' ? 'The curve is inverted across key maturities.' : curve.movement === 'bull_steepening' ? 'The short end is easing faster than the long end, consistent with bull steepening.' : curve.movement === 'bear_flattening' ? 'Yields rose across the curve while the front end rose faster than the long end, a bear-flattening move.' : 'The curve is positive but the full shape remains mixed across maturities.'}</strong></p><div className="curve-history"><b>Recession curve snapshots · lowest 2s10s spread within window</b>{Object.entries(curve.historical).map(([period, snapshot]) => <span key={period}>{period} · {snapshot.representative_date ?? 'N/A'} · {snapshot.coverage}</span>)}</div></div>;
}
