import current from './data/current.json';
import type { DashboardData, Indicator } from './types/dashboard';
import { RecessionGauge } from './components/RecessionGauge';
import { IndicatorGrid } from './components/IndicatorGrid';
import './styles/dashboard.css';
import './styles/current-stress.css';
import './styles/positioning.css';
import './styles/presentation-refresh.css';

const laborIds = ['payrolls', 'sahm-rule', 'initial-claims', 'jolts-hires', 'jolts-quits', 'wage-growth'];
const housingIds = ['housing-starts', 'building-permits', 'new-home-sales', 'months-supply', 'fhfa-home-prices', 'mortgage-rate-30y', 'mortgage-delinquency', 'mortgage-debt-service'];
const ratesIds = ['yield-curve'];
const fragilityIds = ['vix', 'financial-stress', 'credit-conditions', 'margin-debt-gdp'];
const valuationIds = ['public-equity-gdp', 'shiller-cape'];
const pick = (all: Indicator[], ids: string[]) => all.filter((indicator) => ids.includes(indicator.id));
const find = (all: Indicator[], id: string) => all.find((indicator) => indicator.id === id);
const scoreCounts = (all: Indicator[]) => all.reduce((counts, indicator) => { if (indicator.score !== null) counts[indicator.score] += 1; return counts; }, [0, 0, 0]);

function EvidenceChain() { const steps = ['Labor deterioration', 'Consumer pressure', 'Economic slowdown', 'Earnings / cash-flow pressure', 'Asset-price vulnerability']; return <div className="evidence-chain"><div className="section-kicker">EVIDENCE CHAIN · EXPLANATORY ONLY</div><div className="evidence-steps">{steps.map((step, index) => <div className="evidence-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><b>{step}</b>{index < steps.length - 1 && <i aria-hidden="true">→</i>}</div>)}</div></div>; }

function Group({ title, subtitle, indicators, icon }: { title: string; subtitle: string; indicators: Indicator[]; icon: string }) { const scored = indicators.filter((indicator) => indicator.scored); const score = scored.reduce((sum, indicator) => sum + (indicator.score ?? 0), 0); const curve = indicators[0]?.yield_curve_regime; return <section className="topic-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">{icon}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div><span className="topic-score">{scored.length ? `Risk points ${score} / ${scored.length * 2}` : 'Context only'}</span></div>{curve && <div className="curve-regime"><b>Curve regime</b><span>{curve.curve_phase.replace(/_/g, ' ')}</span><span>{curve.steepening_type.replace(/_/g, ' ')}</span><small>2s10s {curve.spread_2s10s_bp > 0 ? '+' : ''}{curve.spread_2s10s_bp} bp · 3m10y {curve.spread_3m10y_bp} bp · {curve.months_since_uninversion ?? '—'} months since un-inversion</small></div>}<IndicatorGrid indicators={indicators} /></section>; }

export default function App() {
  const data = current as DashboardData;
  const labor = pick(data.indicators, laborIds), housing = pick(data.indicators, housingIds), rates = pick(data.indicators, ratesIds), fragility = pick(data.indicators, fragilityIds), valuation = pick(data.indicators, valuationIds);
  const marginDebt = find(data.indicators, 'margin-debt-gdp');
  const consumerInputs = ['sahm-rule', 'initial-claims', 'wage-growth', 'mortgage-delinquency', 'mortgage-debt-service'].map((id) => find(data.indicators, id)).filter(Boolean) as Indicator[];
  const counts = scoreCounts(data.indicators); const updated = new Date(data.generated_at).toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' }); const scoredCount = data.indicators.filter((indicator) => indicator.scored).length;
  return <main>
    <section className="summary-hero merged-summary"><div className="hero-grid-motif" aria-hidden="true" /><div className="merged-summary-head"><div className="summary-copy"><div className="eyebrow">MACRO MONITOR · UNITED STATES</div><h1>US Recession Risk Dashboard</h1><p className="summary-subtitle">A multi-signal view of the U.S. economic cycle, financial stress, and market vulnerability.</p><p className="thesis">Labor conditions are cooling, but the economy is not yet confirming a full recession regime.</p><div className="updated">Last updated · {updated} <span>· Model v{(data as DashboardData & { score_model_version?: number }).score_model_version ?? 1} · {data.data_status === 'ok' ? 'Live data' : 'Sample data'}</span></div></div><div className="summary-score"><span>Cycle risk score</span><strong>{data.risk_score}<small>/100</small></strong><b>{data.regime}</b><div className="score-meta"><span>{data.total_score} of {data.max_score} risk points</span><span>{scoredCount} scored indicators</span></div></div></div><div className="merged-summary-lower"><div className="compact-gauge"><RecessionGauge data={data}/></div><div className="merged-context"><div className="compact-stress"><span>Current Stress · separate confirmation</span><strong>{data.current_stress?.state ?? 'Unavailable'}</strong><small>{data.current_stress?.active_confirmations ?? 0} / 6 confirmations</small></div><div className="status-counts"><span><i className="dot healthy" />{counts[0]} Healthy</span><span><i className="dot warning" />{counts[1]} Warning</span><span><i className="dot recessionary" />{counts[2]} Recessionary</span></div><div className="category-chips">{data.categories.filter((category) => category.max_score > 0).map((category) => <span key={category.id}><b>{category.name}</b><em>{category.risk_score}</em></span>)}</div></div></div><div className="merged-interpretation">{data.summary}</div><EvidenceChain /></section>
    {data.data_status && data.data_status !== 'ok' && <div className="data-warning">Data status: {data.data_status}. {data.warnings?.[0]}</div>}
    <div className="details-kicker"><div className="section-kicker">SIGNAL BREAKDOWN</div><h2>What is driving the picture?</h2></div>
    <Group title="Labor Market" subtitle="Employment, wages, and the demand for workers" indicators={labor} icon="↗" /><Group title="Housing Market" subtitle="Construction, sales, and household financing pressure" indicators={housing} icon="⌂" /><Group title="Bond Market / Rates" subtitle="The yield curve and macro-financial risk" indicators={rates} icon="≈" />
    <section className="fragility-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">◌</span><div><h2>Market Fragility / Stress</h2><p>Public volatility, financial stress, credit conditions, and leverage context.</p></div></div><span className="topic-score">Context only</span></div><IndicatorGrid indicators={fragility} /></section>
    <section className="consumer-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">◌</span><div><h2>Consumer Condition</h2><p>A derived reading of employment, income, and household credit pressure.</p></div></div><span className="topic-score">Interpretation</span></div><div className="consumer-grid">{consumerInputs.map((indicator) => <div className="consumer-signal" key={indicator.id}><b>{indicator.name}</b><span>{indicator.display_value}</span></div>)}<p>The consumer is weakening at the margin, but broad stress remains limited. This panel summarizes existing indicators and does not add points to the main score.</p></div></section>
    <section className="valuation-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">$</span><div><h2>Valuation / Bubble Risk</h2><p>Historically grounded market valuation and leverage context; no composite score or crash timer.</p></div></div><span className="topic-score">Context only</span></div><IndicatorGrid indicators={valuation} />{marginDebt && <div className="valuation-reference"><b>Leverage reference</b><span>{marginDebt.name}: {marginDebt.display_value}</span><small>Referenced from Market Fragility / Stress; counted once in the dashboard data.</small></div>}</section>
    {data.current_stress && <section className="current-stress-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">!</span><div><h2>Current Stress / Break Confirmation</h2><p>Derived timing signals for whether fragility is beginning to break; thresholds are provisional.</p></div></div><span className="topic-score">{data.current_stress.state}</span></div><div className="stress-banner"><strong>{data.current_stress.active_confirmations} of 6 active confirmations</strong><span>{data.current_stress.summary} {data.current_stress.market_confirmation_active ? 'Market/financial stress is present.' : 'No market/financial confirmation is active.'}</span></div><div className="stress-signal-grid">{data.current_stress.signals.map((signal) => <article className="stress-signal" key={signal.id}><div><b>{signal.name}</b><span className={`stress-state ${signal.state}`}>{signal.state}</span></div><strong>{signal.display_value}</strong><p>{signal.explanation}</p><small>{signal.observation_date ?? 'Derived from current curve regime'}</small></article>)}</div></section>}
    {data.berkshire_positioning && <section className="positioning-section"><div className="topic-heading"><div className="topic-title"><span className="topic-icon">B</span><div><h2>Positioning / Sentiment</h2><p>Official Berkshire capital-allocation context; no composite sentiment score.</p></div></div><span className="topic-score">Context only</span></div><article className="berkshire-card"><div className="berkshire-card-heading"><div><h3>Berkshire Capital Allocation</h3><p>{data.berkshire_positioning.report_period} · {data.berkshire_positioning.report_date}</p></div><span className={`source-pill ${data.berkshire_positioning.source_status}`}>{data.berkshire_positioning.source_status}</span></div><div className="berkshire-metrics"><div><span>Liquidity</span><strong>${(data.berkshire_positioning.liquidity_millions / 1000).toFixed(1)}B</strong></div><div><span>Liquidity / Assets</span><strong>{data.berkshire_positioning.liquidity_to_assets_pct.toFixed(1)}%</strong></div><div><span>Equity Purchases YTD</span><strong>${(data.berkshire_positioning.equity_purchases_ytd_millions / 1000).toFixed(1)}B</strong></div><div><span>Equity Sales YTD</span><strong>${(data.berkshire_positioning.equity_sales_ytd_millions / 1000).toFixed(1)}B</strong></div><div><span>Net Equity Flow</span><strong>+${(data.berkshire_positioning.net_equity_flow_ytd_millions / 1000).toFixed(1)}B</strong></div></div><div className="berkshire-read"><b>{data.berkshire_positioning.liquidity_label} Liquidity · {data.berkshire_positioning.equity_flow_label} YTD</b><p>Berkshire is holding an unusually large liquidity reserve while still being a net buyer of equities year-to-date. This is more nuanced than a simple “smart money is exiting” signal.</p></div><footer>{data.berkshire_positioning.source}<span>{data.berkshire_positioning.source_status}</span></footer></article></section>}
    <footer className="site-footer">{data.data_status === 'ok' ? 'Live FRED + manual sample data' : 'Sample data mode'} · Deterministic, rule-based scores.<br />Data obtained through the FRED API / Federal Reserve Bank of St. Louis data service. This dashboard is not affiliated with, endorsed by, or sponsored by the Federal Reserve Bank of St. Louis.</footer>
  </main>;
}
